# Generated by Django 3.2.23 on 2024-01-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('award_win', models.IntegerField(blank=True, default=None, null=True)),
                ('notes', models.TextField(default='')),
                ('no_of_books', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('no_of_pages', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('isbn', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('country_of_origin', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='kitab.author')),
            ],
        ),
    ]
