# Generated by Django 3.2.23 on 2024-01-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
