# Generated by Django 3.2.23 on 2024-01-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_of_birth', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=500, null=True)),
                ('award_win', models.IntegerField(blank=True, default=None, null=True)),
                ('no_of_movies', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_of_birth', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=500, null=True)),
                ('award_win', models.IntegerField(blank=True, default=None, null=True)),
                ('no_of_movies', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_release', models.CharField(blank=True, max_length=20, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('gross_earning_in_mil', models.FloatField(blank=True, default=None, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActedBy+', to='cinema.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cinema.director')),
            ],
        ),
    ]
